export const fakePopularTVShowList = [
  {
    backdrop_path: "/8qlKzvR68dH0ZaJFG9XBEctvvUo.jpg",
    first_air_date: "2011-02-12",
    genre_ids: [35],
    id: 63935,
    name: "Les Mystères de l'amour",
    origin_country: ["FR"],
    original_language: "fr",
    original_name: "Les Mystères de l'amour",
    overview:
      "Les Mystères de l'amour is a French television series originally broadcast by TMC. It was created by Jean-Luc Azoulay. The original French title literally translates to The Mysteries of Love",
    popularity: 1673.551,
    poster_path: "/mtUhIHbhw0GCacVnPam8p4vwejB.jpg",
    vote_average: 5.9,
    vote_count: 8,
  },
  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "Faltu",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Faltu",
    overview:
      "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
    popularity: 2627.101,
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 4.5,
    vote_count: 25,
  },
  {
    backdrop_path: null,
    first_air_date: "2022-11-28",
    genre_ids: [18],
    id: 215315,
    name: "Rabb Se Hai Dua",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "रब्ब से है दुआ",
    overview:
      "Dua and her husband are a perfect married couple in the eyes of their family. However, Dua’s life turns upside down when her husband seeks her permission to marry another woman.",
    popularity: 2517.28,
    poster_path: "/6ikbefd7VeopbBuGgioYMNU5bQj.jpg",
    vote_average: 4.5,
    vote_count: 4,
  },
  {
    backdrop_path: "/3n2TjKw3HrwDqgVgcynvantOfS3.jpg",
    first_air_date: "2023-01-04",
    genre_ids: [18, 10751],
    id: 215103,
    name: "Teri Meri Doriyaan",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "तेरी मेरी डोरियाँ",
    overview:
      "It’s hate at first sight for Sahiba and Angad! But destined to be together, their lives get intertwined by a marriage alliance, and a love-hate story ensues.",
    popularity: 2489.235,
    poster_path: "/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg",
    vote_average: 4.9,
    vote_count: 9,
  },
  {
    backdrop_path: "/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg",
    first_air_date: "2023-05-08",
    genre_ids: [18, 80, 10766],
    id: 209265,
    name: "Terra e Paixão",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Terra e Paixão",
    overview: "",
    popularity: 2829.656,
    poster_path: "/voaKRrYExZNkf1E4FZExU7fTd8w.jpg",
    vote_average: 4.3,
    vote_count: 3,
  },
  {
    backdrop_path: "/jWYzdSv85nncRxfDwYSQKKlnuhG.jpg",
    first_air_date: "2023-03-09",
    genre_ids: [18],
    id: 221949,
    name: "Chashni",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "चाशनी",
    overview:
      "An untoward incident mars the loving relationship between two sisters- Chandni and Roshni. Years later, fate brings them face to face only to find out that they are daughter-in-law and mother-in-law for each other. Thus, begins a typical saas-bahu saga.",
    popularity: 2114.41,
    poster_path: "/qz3mN7SCTVskkDIBwceV4FXv2VC.jpg",
    vote_average: 4.4,
    vote_count: 4,
  },
  {
    backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    first_air_date: "2021-08-03",
    genre_ids: [10766],
    id: 130542,
    name: "Bhagya Lakshmi",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Bhagya Lakshmi",
    overview:
      "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
    popularity: 1489.768,
    poster_path: "/eVaGfVPA85AUrCAQoOLb0kY2SZA.jpg",
    vote_average: 4.9,
    vote_count: 38,
  },
  {
    backdrop_path: "/1Ezn8u1iEOwLHySpwnafinVWeXG.jpg",
    first_air_date: "2023-05-14",
    genre_ids: [18],
    id: 226002,
    name: "Gen Z",
    origin_country: ["CN"],
    original_language: "zh",
    original_name: "後浪",
    overview: "",
    popularity: 1970.8,
    poster_path: "/hquRJB69g1VnRzwX1yWWT7Cz9D6.jpg",
    vote_average: 9,
    vote_count: 1,
  },
  {
    backdrop_path: "/lcSvkJ2Rob3ICIOCUJahw3kgSYZ.jpg",
    first_air_date: "2023-03-14",
    genre_ids: [18],
    id: 216390,
    name: "Woman in a Veil",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "비밀의 여자",
    overview:
      "Jung Gyul Wool loses her vision and ability to walk because of her materialistic husband and his mistress. Despite her shortcomings, she hatches a plot to seek revenge.",
    popularity: 1520.298,
    poster_path: "/5ERr09UrnVm0hdXBeefNVtQMxI.jpg",
    vote_average: 4.7,
    vote_count: 6,
  },
  {
    backdrop_path: "/mAJ84W6I8I272Da87qplS2Dp9ST.jpg",
    first_air_date: "2023-01-23",
    genre_ids: [9648, 18],
    id: 202250,
    name: "Dirty Linen",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Dirty Linen",
    overview:
      "To exact vengeance, a young woman infiltrates the household of an influential family as a housemaid to expose their dirty secrets. However, love will get in the way of her revenge plot.",
    popularity: 1985.899,
    poster_path: "/aoAZgnmMzY9vVy9VWnO3U5PZENh.jpg",
    vote_average: 5.1,
    vote_count: 18,
  },
  {
    backdrop_path: "/1Xm0WqoT0DjZm5JdG2V6YFabrOz.jpg",
    first_air_date: "2023-02-13",
    genre_ids: [10759, 35, 18],
    id: 215803,
    name: "Batang Quiapo",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Batang Quiapo",
    overview:
      "A young man rises to be one of the biggest outlaws in the neighborhood while he navigates his way in life to survive in Quiapo. Hoping to earn the affection of his parents, his feat draws him closer to the truth about his identity.",
    popularity: 1482.746,
    poster_path: "/9McqS8mgMf5NJCAKZIY6J1oOl8y.jpg",
    vote_average: 5.5,
    vote_count: 16,
  },
  {
    backdrop_path: null,
    first_air_date: "2005-09-05",
    genre_ids: [18, 35],
    id: 36361,
    name: "Ulice",
    origin_country: ["CZ"],
    original_language: "cs",
    original_name: "Ulice",
    overview:
      "Ulice is a Czech soap opera produced and broadcast by Nova. In the Czech language Ulice means street.\n\nThe show describes the lives of the Farský, Jordán, Boháč, Nikl, and Liška families and many other people that live in Prague. Their daily battle against real problems of living in a modern world like divorce, love, betrayal and illness or disease. Ulice often shows crime.",
    popularity: 1987.544,
    poster_path: "/3ayWL13P1HeRnyVL9lU9flOdZjq.jpg",
    vote_average: 2.8,
    vote_count: 12,
  },
  {
    backdrop_path: "/xYiI6QEZvx8Z4La1oHvApyZHpOU.jpg",
    first_air_date: "2023-01-16",
    genre_ids: [10766, 35],
    id: 209117,
    name: "Never Give Up",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Vai na Fé",
    overview:
      "Sol is a hardworking woman who has the chance to work as a backing vocalist for a funk singer and return to dancing, as she did in her youth. Torn between family pressure and passion for the stage, she must face the judgment of her church's members and conflicts with her family. The new chance will make her reconnect with her past in many ways, leading her to find her great youth love.",
    popularity: 1921.694,
    poster_path: "/6QNohzb7YUJ6eWZkXAYU8KGIq.jpg",
    vote_average: 7.9,
    vote_count: 10,
  },
  {
    backdrop_path: "/4NcAz1QIqYnhe3u2pnVEVNwfTZf.jpg",
    first_air_date: "2020-10-05",
    genre_ids: [18, 10766, 10751],
    id: 111453,
    name: "Ghum Hai Kisi Ke Pyaar Mein",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "घुम है किसिकी प्यार में",
    overview:
      "Virat sacrifices his love to honour the promise he made to a dying man. Trapped between the past and the present, will he find love beyond the chains of duty?",
    popularity: 1930.943,
    poster_path: "/uNjnoT3RChs2r7O9pDyx7TNBvIj.jpg",
    vote_average: 5.6,
    vote_count: 39,
  },
  {
    backdrop_path: "/mUZqXvIWtyEQ8YrfCiRVqfNYaMl.jpg",
    first_air_date: "2023-05-18",
    genre_ids: [35, 18],
    id: 195670,
    name: "XO, Kitty",
    origin_country: ["US"],
    original_language: "en",
    original_name: "XO, Kitty",
    overview:
      "Teen matchmaker Kitty Song Covey thinks she knows everything there is to know about love. But when she moves halfway across the world to reunite with her long-distance boyfriend, she’ll soon realize that relationships are a lot more complicated when it’s your own heart on the line.",
    popularity: 1053.871,
    poster_path: "/hxvTdKAwv27PUfpXOQp6AwWr6V.jpg",
    vote_average: 8.5,
    vote_count: 127,
  },
  {
    backdrop_path: "/gNPWlhUXhyWiHv9qxr57tvT0WwS.jpg",
    first_air_date: "2014-10-07",
    genre_ids: [18, 10765],
    id: 60735,
    name: "The Flash",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Flash",
    overview:
      'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
    popularity: 1184.637,
    poster_path: "/rg8N7x27Ef6PvlIiioLStf9ZaIO.jpg",
    vote_average: 7.8,
    vote_count: 10433,
  },
  {
    backdrop_path: "/i8NGdMIyZnGNpSHLDtpPwYXidPe.jpg",
    first_air_date: "2020-11-16",
    genre_ids: [18, 10766, 10751],
    id: 113218,
    name: "Imlie",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "इमली",
    overview:
      "All Imlie wanted was to create a name for herself in the city. But upon her arrival, she finds herself caught in the middle of Aditya and Malini's love story.",
    popularity: 1744.722,
    poster_path: "/sltUDXvpDZK3aVIdtkbImhcJv8t.jpg",
    vote_average: 4.6,
    vote_count: 12,
  },
  {
    backdrop_path: "/69Jblm3seQgiPuPQMrJqg9Nxhaz.jpg",
    first_air_date: "2011-01-10",
    genre_ids: [10763, 10767],
    id: 101463,
    name: "Al rojo vivo",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Al rojo vivo",
    overview: "",
    popularity: 1628.887,
    poster_path: "/ag6PmoBxkF2s1uY3An618NCEt3g.jpg",
    vote_average: 3.1,
    vote_count: 11,
  },
  {
    backdrop_path: "/zrv9dK9FQepCS2KCNJ04LYsjsDd.jpg",
    first_air_date: "2023-04-02",
    genre_ids: [10764],
    id: 210479,
    name: "Survivor Québec",
    origin_country: ["CA"],
    original_language: "fr",
    original_name: "Survivor Québec",
    overview: "",
    popularity: 1624.015,
    poster_path: "/cuVZay78P1WkBet12KF8tRJYtp4.jpg",
    vote_average: 8,
    vote_count: 1,
  },
  {
    backdrop_path: "/tio0dduiKFPjOEAf9iPLb9v9MNZ.jpg",
    first_air_date: "2022-11-14",
    genre_ids: [10759, 18],
    id: 211128,
    name: "The Iron Heart",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "The Iron Heart",
    overview:
      "An undercover agent goes on a dangerous mission to bring down a crime ring. Fueled by a bitter and painful past, he along with his allies faces the grueling task that will challenge his resolve and strength.",
    popularity: 1102.972,
    poster_path: "/91V6NI1JXCTDhaSSkoY7T87hk09.jpg",
    vote_average: 6.5,
    vote_count: 6,
  },
  {
    backdrop_path: "/peqIR6V2zZdzp3MEZBCwtqw1Bf2.jpg",
    first_air_date: "2022-11-28",
    genre_ids: [18],
    id: 215426,
    name: "Pyaar Ke Saat Vachan - Dharam Patni",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Pyaar Ke Saat Vachan - Dharam Patni",
    overview:
      "What will happen when Ravi Randhawa, a business tycoon, meets Pratiksha Parekh, a simple school teacher? Will sparks fly? Or is there no happy-ever-after for the opposite personalities?",
    popularity: 1507.411,
    poster_path: "/fMR23wg4yNsTEhqyYIfvzDAOEae.jpg",
    vote_average: 6,
    vote_count: 2,
  },
];
export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/69Jblm3seQgiPuPQMrJqg9Nxhaz.jpg",
    id: 101463,
    name: "Al rojo vivo",
    original_language: "es",
    original_name: "Al rojo vivo",
    overview: "",
    poster_path: "/ag6PmoBxkF2s1uY3An618NCEt3g.jpg",
    media_type: "tv",
    genre_ids: [10763, 10767],
    popularity: 1163.491,
    first_air_date: "2011-01-10",
    vote_average: 3.091,
    vote_count: 11,
    origin_country: ["ES"],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 78911,
    name: "小戏骨：焦裕禄",
    original_language: "zh",
    original_name: "小戏骨：焦裕禄",
    overview: "",
    poster_path: "/mRftESKOsa1NB9Rc8GTNS4mvhUL.jpg",
    media_type: "tv",
    genre_ids: [],
    popularity: 0.626,
    first_air_date: "2015-12-19",
    vote_average: 8,
    vote_count: 1,
    origin_country: [],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 95857,
    name: "Den D",
    original_language: "cs",
    original_name: "Den D",
    overview: "",
    poster_path: null,
    media_type: "tv",
    genre_ids: [10764],
    popularity: 1.4,
    first_air_date: "2009-03-31",
    vote_average: 4,
    vote_count: 1,
    origin_country: ["CZ"],
  },
  {
    adult: false,
    backdrop_path: "/cfyQMPZJEN0TLkG0379Bk03oJ5F.jpg",
    id: 132729,
    name: "魔改造の夜",
    original_language: "ja",
    original_name: "魔改造の夜",
    overview: "",
    poster_path: "/1LWCgEei3aEx1zk3coGnNyMfwcW.jpg",
    media_type: "tv",
    genre_ids: [],
    popularity: 3.694,
    first_air_date: "2020-06-19",
    vote_average: 10,
    vote_count: 1,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/n5OT1a2jItQt3Nqwye1CX2YLJWj.jpg",
    id: 81664,
    name: "History of Weapons",
    original_language: "en",
    original_name: "History of Weapons",
    overview: "",
    poster_path: "/xJc5Uc3JBxA31o4Q0H4cf6X5l7V.jpg",
    media_type: "tv",
    genre_ids: [99, 10768],
    popularity: 0.885,
    first_air_date: "2018-08-01",
    vote_average: 10,
    vote_count: 1,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 100980,
    name: "L'Âne Culotte",
    original_language: "fr",
    original_name: "L'Âne Culotte",
    overview: "",
    poster_path: "/ufUCbW0kbWiqF65rGB4LCPeT2RN.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 4.337,
    first_air_date: "1967-11-27",
    vote_average: 10,
    vote_count: 1,
    origin_country: ["FR"],
  },
  {
    adult: false,
    backdrop_path: "/sb1p0aKxuyzzR7bg22m7xjgw8XO.jpg",
    id: 10594,
    name: "Pete and Gladys",
    original_language: "en",
    original_name: "Pete and Gladys",
    overview:
      "Pete and Gladys is an American situation comedy television series starring Harry Morgan and Cara Williams that aired on CBS on Mondays at 8:00 p.m. Eastern and Pacific time for two seasons, beginning on September 19, 1960. The last episode was broadcast on September 10, 1962.",
    poster_path: "/tB5FovSENT41jsPbYlODxXqFfca.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 16.675,
    first_air_date: "1960-09-19",
    vote_average: 6.5,
    vote_count: 2,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 63636,
    name: "Novellen aus dem wilden Westen",
    original_language: "de",
    original_name: "Novellen aus dem wilden Westen",
    overview: "",
    poster_path: null,
    media_type: "tv",
    genre_ids: [37],
    popularity: 1.854,
    first_air_date: "1969-01-01",
    vote_average: 5,
    vote_count: 1,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: "/iDbgDVinZ0RJmidWGWRKpFP7azb.jpg",
    id: 23974,
    name: "Beach Boys",
    original_language: "ja",
    original_name: "ビーチボーイズ",
    overview:
      "Upon getting thrown out of his girlfriend Fujiko's apartment, Hiromi decides to head for the ocean. En route, he crosses paths with Kaito, an elite employee of a large multinational trading company in Tokyo who is running away from his problems at work after losing a key client. The two stumble into a quiet B&B on the beach run by the aging surfer Masaru and his high-school-aged granddaughter Makoto. Hiromi immediately applies to work there for the summer, and Kaito is forced to join him after he loses his wallet. The two share a room, with Hiromi trying to make friends, and Kaito at first resisting, unimpressed by Hiromi's devil-may-care attitude. Slowly over the ensuing episodes, Kaito becomes more and more at home in this sleepy rural town, and begins to wonder if he should give up his pursuit of success in the big city, and try to relax, and enjoy himself more. When he returns to Tokyo to finish his work, Hiromi and Makoto come to lure him back, but when he returns to the B&B, his boss and girlfriend Sakura likewise come looking for him.",
    poster_path: "/w2tgYlwOHwfi2OioUY1UAcdPjeT.jpg",
    media_type: "tv",
    genre_ids: [18, 35],
    popularity: 7.979,
    first_air_date: "1997-07-07",
    vote_average: 8,
    vote_count: 3,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/62jYrCUgVwgMxm8a2GxrNhvgK71.jpg",
    id: 37079,
    name: "The Man with the Golden Ears",
    original_language: "da",
    original_name: "Manden Med De Gyldne Ører",
    overview: "",
    poster_path: "/lgCjzu9Jv3I7eVaD0da9Otp0vk4.jpg",
    media_type: "tv",
    genre_ids: [18, 35],
    popularity: 0.95,
    first_air_date: "2009-11-04",
    vote_average: 7,
    vote_count: 1,
    origin_country: ["DK"],
  },
];
