export const fakePopularTVShowList = [
  {
    backdrop_path: "/8qlKzvR68dH0ZaJFG9XBEctvvUo.jpg",
    first_air_date: "2011-02-12",
    genre_ids: [35],
    id: 63935,
    name: "Les Mystères de l'amour",
    origin_country: ["FR"],
    original_language: "fr",
    original_name: "Les Mystères de l'amour",
    overview:
      "Les Mystères de l'amour is a French television series originally broadcast by TMC. It was created by Jean-Luc Azoulay. The original French title literally translates to The Mysteries of Love",
    popularity: 1673.551,
    poster_path: "/mtUhIHbhw0GCacVnPam8p4vwejB.jpg",
    vote_average: 5.9,
    vote_count: 8,
  },
];
export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/69Jblm3seQgiPuPQMrJqg9Nxhaz.jpg",
    id: 101463,
    name: "Al rojo vivo",
    original_language: "es",
    original_name: "Al rojo vivo",
    overview: "",
    poster_path: "/ag6PmoBxkF2s1uY3An618NCEt3g.jpg",
    media_type: "tv",
    genre_ids: [10763, 10767],
    popularity: 1163.491,
    first_air_date: "2011-01-10",
    vote_average: 3.091,
    vote_count: 11,
    origin_country: ["ES"],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 78911,
    name: "小戏骨：焦裕禄",
    original_language: "zh",
    original_name: "小戏骨：焦裕禄",
    overview: "",
    poster_path: "/mRftESKOsa1NB9Rc8GTNS4mvhUL.jpg",
    media_type: "tv",
    genre_ids: [],
    popularity: 0.626,
    first_air_date: "2015-12-19",
    vote_average: 8,
    vote_count: 1,
    origin_country: [],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 95857,
    name: "Den D",
    original_language: "cs",
    original_name: "Den D",
    overview: "",
    poster_path: null,
    media_type: "tv",
    genre_ids: [10764],
    popularity: 1.4,
    first_air_date: "2009-03-31",
    vote_average: 4,
    vote_count: 1,
    origin_country: ["CZ"],
  },
  {
    adult: false,
    backdrop_path: "/cfyQMPZJEN0TLkG0379Bk03oJ5F.jpg",
    id: 132729,
    name: "魔改造の夜",
    original_language: "ja",
    original_name: "魔改造の夜",
    overview: "",
    poster_path: "/1LWCgEei3aEx1zk3coGnNyMfwcW.jpg",
    media_type: "tv",
    genre_ids: [],
    popularity: 3.694,
    first_air_date: "2020-06-19",
    vote_average: 10,
    vote_count: 1,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/n5OT1a2jItQt3Nqwye1CX2YLJWj.jpg",
    id: 81664,
    name: "History of Weapons",
    original_language: "en",
    original_name: "History of Weapons",
    overview: "",
    poster_path: "/xJc5Uc3JBxA31o4Q0H4cf6X5l7V.jpg",
    media_type: "tv",
    genre_ids: [99, 10768],
    popularity: 0.885,
    first_air_date: "2018-08-01",
    vote_average: 10,
    vote_count: 1,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 100980,
    name: "L'Âne Culotte",
    original_language: "fr",
    original_name: "L'Âne Culotte",
    overview: "",
    poster_path: "/ufUCbW0kbWiqF65rGB4LCPeT2RN.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 4.337,
    first_air_date: "1967-11-27",
    vote_average: 10,
    vote_count: 1,
    origin_country: ["FR"],
  },
  {
    adult: false,
    backdrop_path: "/sb1p0aKxuyzzR7bg22m7xjgw8XO.jpg",
    id: 10594,
    name: "Pete and Gladys",
    original_language: "en",
    original_name: "Pete and Gladys",
    overview:
      "Pete and Gladys is an American situation comedy television series starring Harry Morgan and Cara Williams that aired on CBS on Mondays at 8:00 p.m. Eastern and Pacific time for two seasons, beginning on September 19, 1960. The last episode was broadcast on September 10, 1962.",
    poster_path: "/tB5FovSENT41jsPbYlODxXqFfca.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 16.675,
    first_air_date: "1960-09-19",
    vote_average: 6.5,
    vote_count: 2,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 63636,
    name: "Novellen aus dem wilden Westen",
    original_language: "de",
    original_name: "Novellen aus dem wilden Westen",
    overview: "",
    poster_path: null,
    media_type: "tv",
    genre_ids: [37],
    popularity: 1.854,
    first_air_date: "1969-01-01",
    vote_average: 5,
    vote_count: 1,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: "/iDbgDVinZ0RJmidWGWRKpFP7azb.jpg",
    id: 23974,
    name: "Beach Boys",
    original_language: "ja",
    original_name: "ビーチボーイズ",
    overview:
      "Upon getting thrown out of his girlfriend Fujiko's apartment, Hiromi decides to head for the ocean. En route, he crosses paths with Kaito, an elite employee of a large multinational trading company in Tokyo who is running away from his problems at work after losing a key client. The two stumble into a quiet B&B on the beach run by the aging surfer Masaru and his high-school-aged granddaughter Makoto. Hiromi immediately applies to work there for the summer, and Kaito is forced to join him after he loses his wallet. The two share a room, with Hiromi trying to make friends, and Kaito at first resisting, unimpressed by Hiromi's devil-may-care attitude. Slowly over the ensuing episodes, Kaito becomes more and more at home in this sleepy rural town, and begins to wonder if he should give up his pursuit of success in the big city, and try to relax, and enjoy himself more. When he returns to Tokyo to finish his work, Hiromi and Makoto come to lure him back, but when he returns to the B&B, his boss and girlfriend Sakura likewise come looking for him.",
    poster_path: "/w2tgYlwOHwfi2OioUY1UAcdPjeT.jpg",
    media_type: "tv",
    genre_ids: [18, 35],
    popularity: 7.979,
    first_air_date: "1997-07-07",
    vote_average: 8,
    vote_count: 3,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/62jYrCUgVwgMxm8a2GxrNhvgK71.jpg",
    id: 37079,
    name: "The Man with the Golden Ears",
    original_language: "da",
    original_name: "Manden Med De Gyldne Ører",
    overview: "",
    poster_path: "/lgCjzu9Jv3I7eVaD0da9Otp0vk4.jpg",
    media_type: "tv",
    genre_ids: [18, 35],
    popularity: 0.95,
    first_air_date: "2009-11-04",
    vote_average: 7,
    vote_count: 1,
    origin_country: ["DK"],
  },
];
